# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'CoolBlue' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoolBlue
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SkeletonView'
  pod 'Cosmos', '~> 16.0'

  target 'CoolBlueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoolBlueUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
